name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Create artifacts directory if not exists
        run: |
          mkdir -p artifacts

      - name: Move artifacts to the artifacts directory
        run: |
          if [ -f target/*.jar ]; then
            mv target/*.jar artifacts/
          else
            echo "No JAR files found"
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use GitHub Secrets for sensitive info
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use GitHub Secrets for sensitive info

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
