# name: Java CI with Maven

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4

#     - name: Set up JDK 21
#       uses: actions/setup-java@v4
#       with:
#         java-version: '21'
#         distribution: 'temurin'
#         cache: maven

#     - name: Build with Maven
#       run: mvn clean package --file pom.xml

#     - name: Deploy JAR to server
#       run: scp -i ${{ secrets.TESTTT }} target/*.jar ubuntu@13.127.122.172:/home/ubuntu

#     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts
#     - name: Update dependency graph
#       uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6












name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Create artifacts directory if not exists
      run: mkdir -p artifacts

    - name: Move artifacts to the artifacts directory
      run: |
        if [ -f target/*.jar ]; then
          mv target/*.jar artifacts/
        else
          echo "No JAR files found"
        fi

    - name: Checkout the repository again for pushing changes
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper pushing

    - name: Configure Git
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"

    - name: Commit and push artifacts to the repository
      run: |
        if [ -d artifacts ] && [ "$(ls -A artifacts)" ]; then
          git add artifacts/
          git commit -m "Add built artifacts" || echo "No changes to commit"
          git push
        else
          echo "No artifacts to commit."
        fi
