name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Create artifacts directory if not exists
      run: echo {{test.mykey}}

    - name: Move artifacts to the artifacts directory
      run: |
        if [ -f target/*.jar ]; then
          mv target/*.jar artifacts/
        else
          echo "No JAR files found"
        fi

    name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t yourusername/yourimage:latest .  # Replace with your Docker Hub username and image name

      - name: Push Docker image to Docker Hub
        run: docker push yourusername/yourimage:latest  # Replace with your Docker Hub username and image name

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ daniel3456 }}
          password: ${{ Daniel123456789@ }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v1.0.0"  # Adjust the version as needed
          name: "Release v1.0.0"  # Adjust the release name as needed
          body: "Release notes for v1.0.0"  # Optional release notes
